# Generated by Django 4.1.5 on 2023-11-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Roles',
        ),
    ]
