# Generated by Django 4.1.5 on 2023-11-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_groups_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
