# Generated by Django 4.1.5 on 2023-11-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_roles_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='vchr_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='vchr_name',
            new_name='name',
        ),
    ]
