# Generated by Django 4.1.5 on 2023-11-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_vchr_code_role_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('alt_phone_number', models.IntegerField(default=None)),
                ('fk_role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.role')),
            ],
        ),
    ]
