# Generated by Django 4.1.5 on 2023-11-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
