# Generated by Django 4.1.5 on 2023-11-18 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0006_delete_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default=None, null=True)),
                ('phone_number', models.IntegerField(default=None, null=True)),
                ('alt_phone_number', models.IntegerField(default=None, null=True)),
                ('fk_role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
