# Generated by Django 4.1.5 on 2023-11-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_userdetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='alt_phone_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
