# Generated by Django 4.1.5 on 2023-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_userdetails_alt_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='int_type',
            field=models.IntegerField(null=True),
        ),
    ]
