# Generated by Django 4.1.5 on 2023-11-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentDetails',
        ),
    ]
