# Generated by Django 4.1.5 on 2023-11-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0010_userdetails_int_type'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_created', models.DateTimeField(auto_now=True)),
                ('dbl_total_amount', models.FloatField()),
                ('fk_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_status', models.IntegerField()),
                ('dbl_rate', models.FloatField()),
                ('int_qty', models.IntegerField()),
                ('fk_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.ordermaster')),
                ('fk_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodproduct')),
            ],
        ),
    ]
