# Generated by Django 4.1.5 on 2023-11-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_rename_fk_order_id_orderdetails_fk_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='dbl_total_amount',
            field=models.FloatField(null=True),
        ),
    ]
