# Generated by Django 4.1.5 on 2023-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_ordermaster_dbl_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='dbl_total_amount',
            field=models.FloatField(),
        ),
    ]
