# Generated by Django 4.1.5 on 2023-11-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_orderstatus_ordermaster_dat_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='int_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='int_qty',
            field=models.IntegerField(blank=True),
        ),
    ]
