# Generated by Django 4.1.5 on 2023-11-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_userdetails_int_type'),
        ('Orders', '0006_ordermaster_int_status_alter_orderdetails_int_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='fk_delivery_agent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_details', to='login.userdetails'),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='fk_updated',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_id', to='login.userdetails'),
        ),
    ]
