# Generated by Django 4.1.5 on 2023-11-21 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0007_alter_ordermaster_fk_delivery_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='fk_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='fk_delivery_agent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='fk_updated',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
